//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfOrganizer.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int id_event { get; set; }
        public Nullable<int> id_users { get; set; }
        public string event_name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> start_datetime { get; set; }
        public Nullable<System.DateTime> end_datetime { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> reminder_datetime { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
