//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfOrganizer.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int id_task { get; set; }
        public Nullable<int> id_users { get; set; }
        public string Taskname { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> creation_datetime { get; set; }
        public Nullable<System.DateTime> due_datetime { get; set; }
        public Nullable<int> id_priority { get; set; }
    
        public virtual Priority Priority { get; set; }
        public virtual Users Users { get; set; }
    }
}
